### ISSUE TITLE
beware of squashing single-commit PRs

### ISSUE THREAD

**Issue by zeke** [zeke/semantic-pull-requests#17]
Also, an edge case for squash commits (via @francisfuzz):

> I was reminded of something I learned about how we treat squash merges recently and would like to share it here in the case it hasn’t been considered by the Electron team.
>
> Squashing a pull request with one commit would use that commit’s message, but squashing a pull request with more than one commit will use the pull request’s title for the commit message.

**Comment by frabonomi** [comment]
Any update on this?

**Comment by zeke** [comment]
I haven't made time to work on this, but if anyone wants to open a PR for it, I'd be happy to review, merge, and deploy it!

**Comment by zeke** [comment]
Sounds good!

**Comment by frabonomi** [comment]
Sorry @zeke, just to better understand the purpose of this repo: in which case would one use the default options and allow merging whenever at least one commit has a semantic message or the title of the PR is semantic?

For this fix what would you suggest to do:
1. fix the behavior of the handler when `titleOnly` option set to `true` in order to check by default the PR title, but in case there's only one commit then check the commit's message
2. create a `squashMerging` option to define the separate behavior

I feel the first option would be the best, but then the `titleOnly` name doesn't make much sense anymore. And I'm also not sure what was the rationale behind that option.

**Comment by kewah** [comment]
@zeke it seems to have been fixed on GitHub side. I ran a test and it uses the PR's title for the commit message 👍 

PR: 
![image](https://user-images.githubusercontent.com/195442/60886867-5004fc00-a253-11e9-8a9f-aee544761dfa.png)


Commit:
![image](https://user-images.githubusercontent.com/195442/60886830-382d7800-a253-11e9-913d-0e7d82b6e1be.png)

**Comment by piratefsh** [comment]
hi @kewah was your merge made as a squash and merge? I'm still facing this issue where GH still autopopulates single-commit squashes with the commit message instead of the PR title (see screenshot)
![Screen Shot 2019-08-07 at 2 44 14 PM](https://user-images.githubusercontent.com/1868400/62657546-beada600-b934-11e9-8877-827788451bc4.png)

**Comment by kewah** [comment]
@piratefsh yes, it was a squashed and merged. I only have that enabled 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/195442/63151844-b3c8d480-c00a-11e9-895c-3996568eda2c.png">

<img width="784" alt="image" src="https://user-images.githubusercontent.com/195442/63152001-18842f00-c00b-11e9-81b0-86fbbecc567c.png">

**Comment by christopherscott** [comment]
i also don't see that this has changed - single commits, when squashed and merged, still seem to default to the commit title

@kewah are you using [Refined Github](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) by any chance?

**Comment by kewah** [comment]
@christopherscott oh right! my bad, I do use Refined GitHub so that explains it

**Comment by zeke** [comment]
Yep this is still an issue. Just bit me again. Would love a PR for this if anyone has the time!

**Comment by zeke** [comment]
Hey y'all. I just deployed a fix for this with #58. Give it a try and let me know if you have any issues!

**Comment by zeke** [comment]
#58 had to be rolled back, so this is still an issue.

**Comment by zeke** [comment]
It works!

![Screen Shot 2020-07-08 at 2 05 31 PM](https://user-images.githubusercontent.com/2289/86970553-6a9ed900-c124-11ea-8349-736157b26e26.png)

**Comment by kunalnagar** [comment]
Hi there,

I'm having issues with single commit PRs still. I have no config file and am using the default GitHub app.

![image](https://user-images.githubusercontent.com/2741371/94934581-f1502180-0499-11eb-86f8-c6c3841e0409.png)

**Comment by kunalnagar** [comment]
@zeke just checking in on what I posted above ☝️
